# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VaultUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('guid', models.CharField(default='', max_length=255)),
                ('google_authenticator_credentials', models.CharField(default='', max_length=255)),
                ('nonce_e', models.CharField(default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_token', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_msg', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('cookie_value', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('password', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.Password')),
            ],
        ),
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='password',
            name='vault',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.Vault'),
        ),
        migrations.AddField(
            model_name='vaultuser',
            name='vault',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vault.Vault'),
        ),
    ]
