# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_auto_20170218_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('success', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('unique_identifier', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='password',
            name='cookie_value',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vaultuser',
            name='guid',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='password',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vaultuser',
            name='vault',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vault.Vault'),
        ),
        migrations.AddField(
            model_name='passwordentity',
            name='password',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.Password'),
        ),
    ]
