# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 05:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_auto_20170301_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='name',
            new_name='domain_name',
        ),
    ]
