# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_auto_20170302_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
