# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_auto_20170220_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='error_msg',
            field=models.CharField(default='', max_length=255),
        ),
    ]
