# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_password_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultuser',
            name='decryption_key_e',
            field=models.CharField(default='', max_length=255),
        ),
    ]
