# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0005_auto_20170220_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultuser',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
