# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 00:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0006_auto_20170221_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginattempt',
            old_name='username',
            new_name='email',
        ),
    ]
