# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0006_vaultuser_salt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaultuser',
            name='decryption_key_e',
        ),
    ]
