# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0007_remove_vaultuser_decryption_key_e'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='external_unique_identifier',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vaultuser',
            name='guid_e',
            field=models.CharField(default='', max_length=255),
        ),
    ]
