# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0007_auto_20170221_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultuser',
            name='nonce',
            field=models.CharField(default='', max_length=255),
        ),
    ]
