# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0008_vaultuser_nonce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordentity',
            name='unique_identifier',
        ),
    ]
