# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0009_remove_passwordentity_unique_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_token', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='vaultuser',
            old_name='nonce',
            new_name='google_authenticator_credentials',
        ),
        migrations.AddField(
            model_name='vaultuser',
            name='nonce_e',
            field=models.CharField(default='', max_length=255),
        ),
    ]
