# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0011_auto_20170317_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalauthentication',
            name='key',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
